/* Local D3 7.9.0; one coordinated state, no external network calls. */
'use strict';
(async function () {
  const $ = id => document.getElementById(id), d3 = window.d3;
  const pct = v => v == null ? 'Unavailable' : d3.format('.1%')(v);
  const num = v => v == null ? 'Unavailable' : d3.format(',')(v);
  const pp = v => d3.format('+.1f')(v) + ' pp';
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let data;
  try {data = await d3.json('data.json');} catch (error) {$('headline').textContent = 'Could not load data. Serve the repository with python3 -m http.server 8000 and open /final/.'; return;}
  const all = data.trials, byId = new Map(all.map(t => [t.nct_id,t]));
  const state = {phase:'',sponsor:'',search:'',selected:localStorage.getItem('stats401-selected') || 'NCT04019704'};
  if (!byId.has(state.selected)) state.selected = all[0].nct_id;
  const teal='#176777', rust='#ac482d', light='#dae7e5';
  function options(id, values) { d3.select('#'+id).selectAll('option.value').data(values).join('option').attr('class','value').attr('value',d=>d).text(d=>d); }
  options('phase',[...new Set(all.map(t=>t.phase))].sort());options('sponsor',[...new Set(all.map(t=>t.sponsor_class))].sort());
  options('comparator',[...new Set(data.pairs.map(t=>t.comparator_type))].sort());
  d3.select('#trial-select').selectAll('option').data(all).join('option').attr('value',t=>t.nct_id).text(t=>t.nct_id+' · '+t.title);
  function eligible() {return all.filter(t=>(!state.phase||t.phase===state.phase)&&(!state.sponsor||t.sponsor_class===state.sponsor)&&(!state.search||(t.nct_id+' '+t.title).toLowerCase().includes(state.search.toLowerCase())));}
  function usable() {return eligible().filter(t=>t.usable);}
  function select(id) {state.selected=id;localStorage.setItem('stats401-selected',id);$('trial-select').value=id;highlight();spotlight();status();}
  function status() {const e=eligible(),u=e.filter(t=>t.usable);$('filter-status').textContent=`Linked filters: ${e.length} / ${all.length} eligible trials; ${u.length} with usable attrition. Phase and sponsor apply across trial views; the model is a fixed analysis.`;const t=byId.get(state.selected);$('selection-status').textContent=`Selected: ${t.nct_id}${e.some(x=>x.nct_id===t.nct_id)?'':' (outside current filters; spotlight retained)'}. Details in section 06.`;}
  function highlight() {d3.selectAll('[data-trial]').classed('selected',function(){return this.dataset.trial===state.selected;});}
  function tooltip(e,text) {const box=$('tooltip');box.textContent=text;box.hidden=false;const rect=box.getBoundingClientRect();box.style.left=Math.max(8,Math.min((e.clientX||20)+14,innerWidth-rect.width-12))+'px';box.style.top=Math.max(8,Math.min((e.clientY||20)+14,innerHeight-rect.height-12))+'px';}
  function bind(sel,id=d=>d.nct_id,description=d=>`${d.nct_id} · ${d.title}\n${pct(d.attrition)} non-completion; ${num(d.completed)} / ${num(d.started)} completed. ${d.period_title}`) {
    return sel.attr('data-trial',id).attr('tabindex',0).attr('role','button').attr('aria-label',d=>description(d)+' Select trial.').classed('trial-mark',true)
      .on('click',(e,d)=>select(id(d))).on('keydown',(e,d)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(id(d));}if(e.key==='Escape')$('tooltip').hidden=true;})
      .on('pointerenter',(e,d)=>tooltip(e,description(d))).on('pointermove',(e,d)=>tooltip(e,description(d))).on('pointerleave',()=>$('tooltip').hidden=true)
      .on('focus',(e,d)=>{const r=e.target.getBoundingClientRect();tooltip({clientX:r.x,clientY:r.y},description(d));}).on('blur',()=>$('tooltip').hidden=true);
  }
  function svg(id,h,label) {const s=d3.select('#'+id).selectAll('svg').data([0]).join('svg').attr('viewBox',`0 0 960 ${h}`).attr('role','group').attr('aria-label',label);s.selectAll('*').remove();s.append('title').text(label);return s;}
  function axis(s,x,y,label) {s.append('g').attr('transform',`translate(0,${y})`).call(d3.axisBottom(x).ticks(5).tickFormat(d=>pct(d)));s.append('text').attr('x',(x.range()[0]+x.range()[1])/2).attr('y',y+42).attr('text-anchor','middle').text(label);}
  function empty(s,text) {s.append('text').attr('x',40).attr('y',60).text(text);}
  // Deterministic collision layout: x encodes rate; y carries no quantitative meaning.
  function swarm(rows,x,center,step=11) {const placed=[];return [...rows].sort((a,b)=>a.attrition-b.attrition||a.nct_id.localeCompare(b.nct_id)).map(t=>{let y=center;for(let k=0;k<rows.length*2+1;k++){const offset=k===0?0:(k%2?1:-1)*Math.ceil(k/2)*step;y=center+offset;if(placed.every(p=>(p.x-x(t.attrition))**2+(p.y-y)**2>=step**2))break;}const p={...t,x:x(t.attrition),y};placed.push(p);return p;});}
  function distribution() {const rows=usable(),x=d3.scaleLinear().domain([0,1]).range([45,915]);const points=swarm(rows,x,0),extent=d3.extent(points,d=>d.y),low=extent[0]||0,high=extent[1]||0,offset=40-low,h=Math.max(245,high-low+145),base=h-60;const s=svg('distribution',h,'Distribution of trial non-completion rates');
    if(!rows.length){empty(s,'No usable trials match these filters.');$('distribution-note').textContent='No usable trial rates in this selection.';return;}
    const sorted=rows.map(t=>t.attrition).sort(d3.ascending),q1=d3.quantile(sorted,.25),q3=d3.quantile(sorted,.75),med=d3.median(sorted),S=d3.sum(rows,t=>t.started),C=d3.sum(rows,t=>t.completed);
    s.append('rect').attr('x',x(q1)).attr('y',20).attr('width',x(q3)-x(q1)).attr('height',base-20).attr('fill',light).attr('opacity',.55);
    s.append('line').attr('x1',x(med)).attr('x2',x(med)).attr('y1',15).attr('y2',base).attr('stroke',teal).attr('stroke-dasharray','4 4');
    if(rows.some(t=>t.reported_zero_completions))s.append('text').attr('x',x(1)).attr('y',15).attr('text-anchor','end').text('Zero completions reported ↓');
    bind(s.selectAll('circle').data(points).join('circle').attr('cx',d=>d.x).attr('cy',d=>d.y+offset).attr('r',4.8).attr('fill',d=>d.reported_zero_completions?rust:teal).attr('opacity',.85));axis(s,x,base,'Non-completion in the registered period');
    $('distribution-note').textContent=`${rows.length} trials · median ${pct(med)} · middle half ${pct(q1)}–${pct(q3)}. Pooling participant counts gives ${pct(1-C/S)} (${num(S-C)} / ${num(S)}), a different summary.`;
  }
  function groups() {const field=$('group-by').value,e=eligible(),u=usable(),keys=[...new Set(e.map(t=>t[field]))].sort(),x=d3.scaleLinear().domain([0,1]).range([310,915]);$('group-note').textContent=field==='sponsor_class'?'In the full snapshot, strict extraction retains 52/155 industry-sponsored trials versus 28/43 in OTHER. This selection difference limits interpretation of attrition contrasts.':field==='intervention_types'?'Drug-only records dominate: 66 of 82 usable trials. Every other intervention-type combination has four or fewer usable trials; compare individual records, not supposed treatment rankings.':'Distributions overlap. Inspect sample sizes and the usable/eligible fraction before interpreting a category difference.';const layouts=keys.map(k=>{const r=u.filter(t=>t[field]===k),points=swarm(r,x,0,10),ex=d3.extent(points,d=>d.y);return {key:k,rows:r,points,lo:ex[0]||0,hi:ex[1]||0};});let cursor=20;layouts.forEach(g=>{g.center=cursor-g.lo+18;cursor+=Math.max(55,g.hi-g.lo+42);});const s=svg('subgroups',cursor+70,'Attrition distributions by '+field);if(!keys.length){empty(s,'No trials in this selection.');return;}
    layouts.forEach(g=>{const n=e.filter(t=>t[field]===g.key).length;s.append('text').attr('x',8).attr('y',g.center+4).text(g.key.replaceAll('_',' ')+' · '+g.rows.length+'/'+n);s.append('line').attr('x1',310).attr('x2',915).attr('y1',g.center).attr('y2',g.center).attr('stroke','#e4e7e3');bind(s.selectAll('circle.g-'+g.center).data(g.points).enter().append('circle').attr('cx',d=>d.x).attr('cy',d=>d.y+g.center).attr('r',4).attr('fill',teal).attr('opacity',.8));if(g.rows.length>=5){const m=x(d3.median(g.rows,t=>t.attrition));s.append('line').attr('x1',m).attr('x2',m).attr('y1',g.center-15).attr('y2',g.center+15).attr('stroke',rust).attr('stroke-width',2);}});axis(s,x,cursor,'Non-completion · orange tick = median when n ≥ 5');
  }
  function relationship() {const key=$('relationship-x').value,allrows=usable(),rows=allrows.filter(t=>t[key]!=null),s=svg('relationship',350,'Trial characteristics and attrition');$('relationship-note').textContent=`${rows.length} with this field; ${allrows.length-rows.length} unavailable among ${allrows.length} usable filtered trials. Each point is a trial.`;if(!rows.length){empty(s,'No usable values.');return;}
    let domain=d3.extent(rows,t=>t[key]);if(domain[0]===domain[1])domain=[domain[0]-1,domain[1]+1];const x=d3.scaleLinear().domain(domain).nice().range([70,920]),y=d3.scaleLinear().domain([0,1]).range([280,25]);s.append('g').attr('transform','translate(0,280)').call(d3.axisBottom(x).ticks(5).tickFormat(d3.format(key==='completion_year'?'d':',.0f')));s.append('g').attr('transform','translate(70,0)').call(d3.axisLeft(y).tickFormat(pct).ticks(5));bind(s.selectAll('circle').data(rows).join('circle').attr('cx',t=>x(t[key])).attr('cy',t=>y(t.attrition)).attr('r',5).attr('fill',teal).attr('opacity',.7));s.append('text').attr('x',490).attr('y',329).attr('text-anchor','middle').text($('relationship-x').selectedOptions[0].text);}
  function dumbbell() {const ids=new Set(eligible().map(t=>t.nct_id));let rows=data.pairs.filter(p=>ids.has(p.nct_id)&&(!$('comparator').value||p.comparator_type===$('comparator').value));const mode=$('pair-sort').value;rows.sort((a,b)=>mode==='id'?a.nct_id.localeCompare(b.nct_id):(mode==='absolute'?b.absolute_difference_pp-a.absolute_difference_pp:b.difference_pp-a.difference_pp)||a.nct_id.localeCompare(b.nct_id));const s=svg('dumbbell',Math.max(170,rows.length*29+100),'Paired experimental and comparator attrition');const x=d3.scaleLinear().domain([0,1]).range([170,800]);axis(s,x,35,'');s.append('text').attr('x',830).attr('y',35).text('Δ (pp)');
    $('pair-note').textContent=`${rows.length} paired trials in this selection${rows.length?`; median absolute difference ${d3.format('.1f')(d3.median(rows,d=>d.absolute_difference_pp))} pp`:''}.`;
    if(!rows.length){empty(s,'No unambiguous pairs match these filters.');return;}
    const r=bind(s.selectAll('g.pair').data(rows,d=>d.nct_id).join('g').attr('class','pair').attr('transform',(d,i)=>`translate(0,${80+i*29})`),d=>d.nct_id,d=>`${d.nct_id}: ${d.experimental_label} ${pct(d.experimental_attrition)} (${d.experimental_started-d.experimental_completed}/${d.experimental_started}); ${d.comparator_label} ${pct(d.comparator_attrition)} (${d.comparator_started-d.comparator_completed}/${d.comparator_started}); difference ${pp(d.difference_pp)}.`);
    r.append('rect').attr('x',0).attr('y',-12).attr('width',940).attr('height',26).attr('fill','transparent').attr('stroke','none');r.append('text').attr('x',5).attr('y',4).text(d=>d.nct_id);r.append('line').attr('x1',d=>x(d.experimental_attrition)).attr('x2',d=>x(d.comparator_attrition)).attr('stroke','#84999b').attr('stroke-width',2);r.append('path').attr('d',d3.symbol().type(d3.symbolDiamond).size(55)).attr('transform',d=>`translate(${x(d.comparator_attrition)},0)`).attr('fill',teal);r.append('circle').attr('cx',d=>x(d.experimental_attrition)).attr('r',4.5).attr('fill',rust);r.append('text').attr('x',830).attr('y',4).text(d=>pp(d.difference_pp));}
  function model() {const rows=data.model.filter(m=>m.sensitivity===$('model-version').value&&m.term!=='Intercept');const s=svg('coefficients',240,'Adjusted attrition associations with bootstrap intervals');const extent=d3.extent(data.model.filter(m=>m.term!=='Intercept').flatMap(m=>[m.bootstrap_low_pp,m.bootstrap_high_pp]));const x=d3.scaleLinear().domain([Math.floor(extent[0]/5)*5,Math.ceil(extent[1]/5)*5]).range([330,900]);s.append('line').attr('x1',x(0)).attr('x2',x(0)).attr('y1',15).attr('y2',175).attr('stroke','#899');const labels={log2_started:'Per doubling of participants started',industry_vs_other:'Industry vs other sponsor classes',phase_III_present:'Any Phase III vs no Phase III'};rows.forEach((m,i)=>{const y=40+i*52;s.append('text').attr('x',5).attr('y',y+4).text(labels[m.term]);s.append('line').attr('x1',x(m.bootstrap_low_pp)).attr('x2',x(m.bootstrap_high_pp)).attr('y1',y).attr('y2',y).attr('stroke',teal).attr('stroke-width',3);s.append('circle').attr('cx',x(m.estimate_pp)).attr('cy',y).attr('r',6).attr('fill',rust).append('title').text(`${pp(m.estimate_pp)}; 95% interval ${pp(m.bootstrap_low_pp)} to ${pp(m.bootstrap_high_pp)}`);});s.append('g').attr('transform','translate(0,185)').call(d3.axisBottom(x).ticks(7));s.append('text').attr('x',630).attr('y',230).attr('text-anchor','middle').text('Adjusted difference in non-completion (percentage points)');$('model-note').textContent=`Fixed model: n=${rows[0].n}; unaffected by the linked phase/sponsor filters. Bars: 95% percentile intervals from ${rows[0].bootstrap_replicates} trial-level bootstrap samples. Orange dots: estimates. Zero means no adjusted difference.`;}
  function matrix() {let rows=eligible();const mode=$('report-status').value;if(mode!=='all')rows=rows.filter(t=>mode==='usable'?t.usable:!t.usable);rows.sort((a,b)=>$('report-sort').value==='year'?(a.completion_year??9999)-(b.completion_year??9999)||a.nct_id.localeCompare(b.nct_id):a.nct_id.localeCompare(b.nct_id));const keys=['participant_flow','completion_counts_present','reason_counts_present','numeric_primary_results','single_period','exact_arm_mapping','usable_attrition'],labels=['Flow','Completion','Reasons','Primary result','One period','Arm match','Usable rate'];const s=svg('matrix',Math.max(160,rows.length*24+75),'Registry reporting and analytical eligibility matrix');const x=d3.scaleBand().domain(keys).range([165,940]).padding(.12);keys.forEach((k,i)=>s.append('text').attr('x',x(k)+x.bandwidth()/2).attr('y',25).attr('text-anchor','middle').text(labels[i]));s.append('line').attr('x1',x('single_period')-9).attr('x2',x('single_period')-9).attr('y1',5).attr('y2',rows.length*24+65).attr('stroke','#b8c2be');
    const row=bind(s.selectAll('g.row').data(rows,d=>d.nct_id).join('g').attr('class','row').attr('transform',(d,i)=>`translate(0,${53+i*24})`),d=>d.nct_id,d=>`${d.nct_id}: ${keys.map((k,i)=>labels[i]+': '+(d.reporting[k]?'yes':'no')).join('; ')}. ${d.qc_flags.replaceAll('_',' ').replaceAll(';','; ')||'All attrition checks passed'}`);row.append('text').attr('x',4).attr('y',4).text(d=>d.nct_id);row.each(function(t){const g=d3.select(this);keys.forEach(k=>{g.append('rect').attr('x',x(k)).attr('y',-9).attr('width',x.bandwidth()).attr('height',18).attr('fill',t.reporting[k]?light:'#f3f1ec').attr('stroke','none');g.append('text').attr('x',x(k)+x.bandwidth()/2).attr('y',4).attr('text-anchor','middle').text(t.reporting[k]?'✓':'−');});});$('report-note').textContent=`${rows.length} trials shown: ${rows.filter(t=>t.reporting.reason_counts_present).length} with numeric reason entries; ${rows.filter(t=>t.reporting.numeric_primary_results).length} with numeric primary results; ${rows.filter(t=>t.usable).length} pass all attrition checks. Source reporting and extraction rules are separate. Missing years sort last.`;}
  function spotlight() {const t=byId.get(state.selected);$('trial-select').value=t.nct_id;const a=t.arms;
    $('trial-detail').innerHTML=`<h3>${esc(t.title)}</h3><p><a target="_blank" rel="noopener" href="https://clinicaltrials.gov/study/${t.nct_id}?tab=results">${t.nct_id} · registry record ↗</a></p><p>${esc(t.phase)} · ${esc(t.sponsor_class)} · ${esc(t.masking)} masking · ${esc(t.allocation)} · ${num(t.protocol_arm_count)} protocol arms</p><p class="small">${esc(t.interventions)}<br>Enrollment: ${num(t.enrollment)} (${esc(t.enrollment_type)}); participants started: ${num(t.started)}; completed: ${num(t.completed)}. Completion year: ${t.completion_year??'unavailable'}; listed locations: ${num(t.site_count)}.</p><p>${t.usable?`Reported-period non-completion: <strong>${pct(t.attrition)}</strong>. Period: ${esc(t.period_title)}.`:`Attrition not calculated: ${esc(t.qc_flags.replaceAll(';','; '))}.`}</p>${t.reported_zero_completions?'<p class="warning">Reporting anomaly: this source reports zero completions in every arm. Arithmetic is valid; real-world interpretation is unresolved.</p>':''}<p>${t.pair?`Experimental: ${pct(t.pair.experimental_attrition)}; comparator: ${pct(t.pair.comparator_attrition)}; Δ ${pp(t.pair.difference_pp)}.`:`No defensible two-arm treatment–comparator contrast: ${esc(t.pair_status.replaceAll('_',' '))}.`}</p>`;
    const s=svg('flow',Math.max(160,a.length*80+60),'Selected-trial participant completion by arm');if(!t.usable){empty(s,'Flow comparison deferred: period, counts or mapping requires review.');}else {const x=d3.scaleLinear().domain([0,1]).range([10,930]);a.forEach((arm,i)=>{const y=35+i*80;s.append('text').attr('x',10).attr('y',y-12).text(arm.flow_title+' · '+arm.arm_type);const complete=arm.completed/arm.started;s.append('rect').attr('x',10).attr('y',y).attr('width',x(complete)-10).attr('height',21).attr('fill',teal);s.append('rect').attr('x',x(complete)).attr('y',y).attr('width',x(1)-x(complete)).attr('height',21).attr('fill',rust);s.append('text').attr('x',10).attr('y',y+42).text(`${num(arm.completed)} completed / ${num(arm.started)} started · ${num(arm.noncompleted)} not completed (${pct(arm.attrition)})`);});}
    const r=[];for(const arm of a){const reasons=t.reasons.filter(r=>r.group_id===arm.group_id);for(const reason of reasons){let value=num(reason.count);if($('reason-mode').value==='share')value=arm.reason_reconciles&&arm.noncompleted>0?pct(reason.count/arm.noncompleted):'Not defined';r.push(`<tr><td>${esc(arm.flow_title)}</td><td>${esc(reason.reason_label)}</td><td>${value}</td><td>${arm.reason_reconciles===true?'Reconciles':arm.reason_reconciles===false?'Does not reconcile':'Unavailable'}</td></tr>`);}}
    $('reason-detail').innerHTML=`<p class="small">Teal = completed; rust = non-completed. Bars use each arm’s own STARTED denominator. Original reason labels below are not merged. Shares require reasons to reconcile and a positive non-completion denominator.</p>${r.length?`<table><thead><tr><th>Arm</th><th>Original reason</th><th>${$('reason-mode').value==='share'?'Share of non-completions':'Reported participants'}</th><th>Reason sum vs non-completion</th></tr></thead><tbody>${r.join('')}</tbody></table>`:'<p>No extracted single-period reason entries. This does not mean no participants left; multi-period data remain in the raw record.</p>'}`;
    $('outcome-detail').innerHTML=t.primary_outcomes.map(o=>`<h3>${esc(o.title)}</h3><p>${esc(o.time_frame)} · ${esc(o.parameter)} · ${esc(o.unit)}</p><p class="small">Population: ${esc(o.population)||'Not stated'}. ${o.numeric_cells} numeric cells; outcome-to-flow group link: ${o.exact_flow_group_link?'exact':'not established'}. ${esc(o.description)}</p><table><thead><tr><th>Outcome group</th><th>Reported value</th><th>Reported dispersion (${esc(o.dispersion)||'unspecified'})</th><th>Class / category</th></tr></thead><tbody>${o.measurements.map(m=>`<tr><td>${esc(m.group_title)}</td><td>${esc(m.raw_value)}</td><td>${esc(m.spread)||'Not stated'}</td><td>${esc(m.class_title)} / ${esc(m.category_title)}</td></tr>`).join('')}</tbody></table><p class="small">Values are reported in ${esc(o.unit)} using ${esc(o.parameter)}. They are not harmonized effect estimates; analysis denominators are in the downloadable outcome-cell table.</p>`).join('')||'<p>No structured primary outcome identified.</p>';
  }
  function render(){distribution();groups();relationship();dumbbell();matrix();status();highlight();}
  for(const [id,key] of [['phase','phase'],['sponsor','sponsor'],['search','search']])$(id).addEventListener(id==='search'?'input':'change',e=>{state[key]=e.target.value;render();});
  for(const [id,fn] of [['group-by',groups],['relationship-x',relationship],['pair-sort',dumbbell],['comparator',dumbbell],['report-status',matrix],['report-sort',matrix]])$(id).addEventListener('change',()=>{fn();highlight();});
  $('model-version').addEventListener('change',model);$('trial-select').addEventListener('change',e=>select(e.target.value));$('reason-mode').addEventListener('change',spotlight);
  $('reset').addEventListener('click',()=>{state.phase=state.sponsor=state.search='';['phase','sponsor','search','comparator'].forEach(id=>$(id).value='');$('report-status').value='all';$('report-sort').value='id';$('pair-sort').value='absolute';select('NCT04019704');render();});
  const sm=data.summary;$('headline').innerHTML=`<div><strong>${sm.eligible_trials}</strong><span>eligible trials</span></div><div><strong>${sm.usable.n}</strong><span>usable trial rates</span></div><div><strong>${sm.paired_trials}</strong><span>unambiguous arm pairs</span></div><div><strong>${pct(sm.usable.median)}</strong><span>median trial non-completion</span></div>`;
  $('outcome-note').textContent=`${sm.reporting_counts.numeric_primary_results} / ${sm.eligible_trials} trials have at least one numeric primary-result cell. There are ${sm.primary_outcome_rows} primary outcomes with ${sm.unique_primary_titles} distinct titles. All ${sm.paired_trials} paired trials have numeric primary results; only ${sm.candidate_madrs_trials} pass a preliminary two-arm MADRS-change screen. These are review candidates, not a harmonized analysis cohort.`;
  render();model();spotlight();document.documentElement.dataset.ready='true';
})();
