/* Coordinated-map browser validation. Requires Playwright and Google Chrome.
   Run against a root-served repository; screenshots/results go to /private/tmp. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'}),errors=[],failed=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('favicon.ico'))failed.push([r.status(),r.url()]);});
const base=process.env.SITE_URL||'http://127.0.0.1:8000/final/',data=JSON.parse(fs.readFileSync('final/data.json'));
const visibleProse=()=>page.evaluate(()=>[...document.querySelectorAll('p')].filter(el=>{for(let a=el;a;a=a.parentElement){if(a.tagName==='DETAILS'&&!a.open)return false;}return el.getClientRects().length>0&&getComputedStyle(el).visibility!=='hidden';}).map(e=>e.innerText).join(' ').trim().split(/\s+/).filter(Boolean).length);
await page.goto(new URL('../editorial-2026-09-28/',base).href);await page.waitForSelector('html[data-ready="true"]');const previousWords=await visibleProse();assert.equal(await page.locator('#dumbbell g.pair').count(),38);
await page.goto(base);await page.waitForSelector('html[data-ready="true"]');const currentWords=await visibleProse();assert.ok(currentWords<=previousWords*.5,`Prose ${currentWords}/${previousWords}`);
const count=s=>page.locator(s).count();assert.equal(await count('#attrition-map circle.trial-point'),38);assert.equal(await count('#distribution circle'),82);assert.equal(await count('#gap-distribution circle'),38);assert.equal(await count('#dumbbell g.pair'),38);assert.equal(await count('#matrix g.row'),201);
assert.equal(await page.locator('#compare-details').getAttribute('open'),null);assert.equal(await page.locator('#characteristics-details').getAttribute('open'),null);assert.equal(await page.locator('#reporting-details').getAttribute('open'),null);
// Independently reconstruct every map position from its verified trial/pair values and SVG dimensions.
const plotted=await page.locator('#attrition-map circle.trial-point').evaluateAll(es=>es.map(e=>({id:e.dataset.trial,cx:+e.getAttribute('cx'),cy:+e.getAttribute('cy')})));
const dims=await page.locator('#attrition-map svg').evaluate(e=>({w:e.viewBox.baseVal.width,h:e.viewBox.baseVal.height}));
for(const p of plotted){const t=data.trials.find(t=>t.nct_id===p.id),pair=data.pairs.find(t=>t.nct_id===p.id);assert.ok(Math.abs(p.cx-(60+(dims.w-24-60)*pair.absolute_difference_pp/30))<1e-7);assert.ok(Math.abs(p.cy-((dims.h-69)-(dims.h-69-34)*t.attrition))<1e-7);}
assert.ok(Math.abs(+(await page.locator('.median-reference').getAttribute('data-value'))-data.summary.pair_median_absolute_pp)<1e-12);
const assertSelection=async id=>{assert.equal(await page.locator('#trial-detail').getAttribute('data-nct'),id);const t=data.trials.find(t=>t.nct_id===id);for(const view of ['#attrition-map','#distribution','#gap-distribution','#dumbbell','#matrix']){const applicable=view==='#matrix'||(view==='#distribution'?t.usable:!!t.pair);assert.equal(await count(`${view} [data-trial="${id}"].selected`),applicable?1:0,view);}if(t.usable)assert.equal(await page.locator('[data-metric="overall"]').innerText(),(t.attrition*100).toFixed(1)+'%');if(t.pair){assert.equal(await page.locator('#participant-bars .arm-block').count(),2);for(const arm of t.arms){const bar=page.locator(`.arm-block[data-group="${arm.group_id}"]`);assert.match(await bar.innerText(),new RegExp(`${arm.completed} completed / ${arm.started} started`));const w=await bar.locator('.completed-segment').evaluate(el=>el.getBoundingClientRect().width/el.parentElement.getBoundingClientRect().width);assert.ok(Math.abs(w-arm.completed/arm.started)<.002);}}};
await assertSelection('NCT04019704');
// Hover never persists selection; click/keyboard does.
await page.locator('#attrition-map [data-trial="NCT02176291"]').hover();await assertSelection('NCT04019704');await page.locator('#attrition-map [data-trial="NCT02176291"]').click();await assertSelection('NCT02176291');
await page.locator('#attrition-map [data-trial="NCT03433339"]').focus();await page.keyboard.press('Enter');await assertSelection('NCT03433339');await page.keyboard.press('Escape');assert.equal(await page.locator('#tooltip').isVisible(),false);
await page.fill('#search','AXS-05');await page.locator('#search-results button[data-nct="NCT04019704"]').click();await assertSelection('NCT04019704');
await page.fill('#search','not-a-trial-xyz');assert.match(await page.locator('#search-results').innerText(),/No matching/);assert.equal(await count('#attrition-map circle.trial-point'),38);await page.keyboard.press('Escape');
await page.fill('#search','NCT00149643');assert.equal(await page.locator('#trial-detail').getAttribute('data-nct'),'NCT00149643');assert.match(await page.locator('#trial-detail').innerText(),/Flagged/);await assertSelection('NCT00149643');assert.match(await page.locator('#selection-status').innerText(),/not plotted/);assert.match(await page.locator('#gap-note').innerText(),/no reliable pair/);
await page.reload();await page.waitForSelector('html[data-ready="true"]');assert.equal(await page.locator('#trial-detail').getAttribute('data-nct'),'NCT00149643');
await page.locator('#compare-details>summary').click();for(const mode of ['signed','absolute','id']){await page.selectOption('#pair-sort',mode);const rows=await page.locator('#dumbbell g.pair').evaluateAll(es=>es.map(e=>e.__data__));assert.ok(rows.every((r,i)=>!i||(mode==='signed'?rows[i-1].difference_pp>=r.difference_pp:mode==='absolute'?rows[i-1].absolute_difference_pp>=r.absolute_difference_pp:rows[i-1].nct_id<=r.nct_id)));}
await page.locator('#dumbbell [data-trial="NCT03866174"]').click();await assertSelection('NCT03866174');
await page.locator('#distribution [data-trial="NCT04019704"]').focus();await page.keyboard.press('Enter');await assertSelection('NCT04019704');await page.locator('#gap-distribution [data-trial="NCT02176291"]').focus();await page.keyboard.press('Enter');await assertSelection('NCT02176291');
await page.locator('#reporting-details>summary').click();assert.equal(await count('#matrix .source-status'),804);assert.equal(await count('#matrix .rule-status'),603);await page.selectOption('#report-status','review');assert.equal(await count('#matrix g.row'),119);const reviewId=await page.locator('#matrix g.row').first().getAttribute('data-trial');await page.locator('#matrix g.row').first().click();assert.equal(await page.locator('#trial-detail').getAttribute('data-nct'),reviewId);assert.match(await page.locator('#trial-detail').innerText(),/No validated/);await page.selectOption('#report-status','all');
await page.locator('#characteristics-details>summary').click();await page.selectOption('#model-version','omit_zero_completions');assert.match(await page.locator('#model-note').innerText(),/n=81/);
await page.fill('#search','NCT02176291');await page.locator('#record-details>summary').click();await page.locator('#reason-details>summary').click();await page.selectOption('#reason-mode','share');assert.match(await page.locator('#reason-detail').innerText(),/20.0%/);
await page.click('#reset');await page.reload();await page.waitForSelector('html[data-ready="true"]');await page.evaluate(()=>scrollTo(0,0));await page.mouse.move(1,1);await page.screenshot({path:'/private/tmp/stats401-map-desktop.png',fullPage:true});await page.locator('.main-analysis').screenshot({path:'/private/tmp/stats401-map-main.png'});
const layout=await page.evaluate(()=>{const m=document.querySelector('.map-area').getBoundingClientRect(),p=document.querySelector('#selected-panel').getBoundingClientRect();return {mapRight:m.right,panelLeft:p.left,mapTop:m.top,panelTop:p.top};});assert.ok(layout.panelLeft>layout.mapRight);assert.ok(Math.abs(layout.mapTop-layout.panelTop)<2);
for(const width of [390,768]){await page.setViewportSize({width,height:844});await page.goto(base);await page.waitForSelector('html[data-ready="true"]');await page.waitForTimeout(180);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal page overflow');await page.screenshot({path:`/private/tmp/stats401-map-${width}.png`,fullPage:true});if(width===390){assert.ok(await page.evaluate(()=>document.querySelector('#selected-panel').getBoundingClientRect().top>document.querySelector('#attrition-map').getBoundingClientRect().bottom));await page.locator('#attrition-map [data-trial="NCT02176291"]').click();assert.equal(await page.locator('#trial-detail').getAttribute('data-nct'),'NCT02176291');}}
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
const result={result:'PASS',edition:'coordinated-map-2026-09-28',browser_version:await browser.version(),source_sha256:Object.fromEntries(['final/index.html','final/app.js','final/style.css','final/data.json','final/eligibility.json'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')])),map_points:38,all_map_coordinates_match_verified_exports:true,selection_views:['map','panel','overall distribution','gap distribution','dumbbell','matrix'],participant_bars_source_checked:true,hover_does_not_select:true,search_click_keyboard_persistence:true,nonpaired_never_zero_filled:true,sorting_and_secondary_controls:true,desktop_adjacent_panel:true,mobile_widths:[390,768],mobile_map_first:true,prose_metric:'Visible paragraph words, including below-fold copy; closed disclosures excluded; same default selected trial.',previous_visible_prose_words:previousWords,current_visible_prose_words:currentWords,prose_reduction_percent:100*(1-currentWords/previousWords),backup_loads:true,javascript_errors:errors,failed_assets:failed};fs.writeFileSync('/private/tmp/stats401-browser-validation.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
