/* Browser integration tests for the frozen five-view dashboard.
   NODE_PATH must expose Playwright; Google Chrome and a root-served repo are required. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
(async()=>{
 const data=JSON.parse(fs.readFileSync('five-view/data.json')),pairs=data.trials.filter(t=>t.pair),base=process.env.SITE_URL||'http://127.0.0.1:8000/five-view/';
 const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'}),errors=[],failed=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('favicon.ico'))failed.push([r.status(),r.url()]);});
 await page.goto(base);await page.waitForSelector('html[data-ready="true"]');
 const snapshot=()=>page.evaluate(()=>window.dashboardSnapshot()),count=s=>page.locator(s).count();
 assert.equal(await count('.primary-view'),5);assert.equal(await count('#attrition-map circle.trial-point'),38);assert.equal(await count('#parallel .parallel-line'),38);assert.equal(await count('#parallel .pc-axis'),4);assert.equal(await count('#parallel .missing-year'),1);assert.equal(await count('#dumbbell g.pair'),38);assert.equal(await count('#matrix g.row'),201);
 assert.equal(await count('#matrix .source-status'),804);assert.equal(await count('#matrix .rule-status'),603);
 // Every polyline is keyed to the same 38 NCT IDs, with a broken final segment for missing year.
 assert.deepEqual((await page.locator('#parallel .parallel-line').evaluateAll(es=>es.map(e=>e.dataset.trial))).sort(),pairs.map(t=>t.nct_id).sort());
 const paths=await page.locator('#parallel .parallel-line').evaluateAll(es=>es.map(e=>({id:e.dataset.trial,d:e.getAttribute('d')})));
 for(const p of paths){assert.ok(!/NaN|undefined/.test(p.d));assert.equal((p.d.match(/L/g)||[]).length,p.id==='NCT01488071'?2:3);}
 const dims=await page.locator('#attrition-map svg').evaluate(e=>({w:e.viewBox.baseVal.width,h:e.viewBox.baseVal.height}));
 for(const p of await page.locator('#attrition-map circle.trial-point').evaluateAll(es=>es.map(e=>({id:e.dataset.trial,x:+e.getAttribute('cx'),y:+e.getAttribute('cy')})))){const t=pairs.find(t=>t.nct_id===p.id);assert.ok(Math.abs(p.x-(60+(dims.w-84)*t.pair.absolute_difference_pp/30))<1e-7);assert.ok(Math.abs(p.y-(dims.h-69-(dims.h-103)*t.attrition))<1e-7);}
 const selected=async id=>{assert.equal((await snapshot()).selectedTrial,id);assert.equal(await page.locator('#trial-detail').getAttribute('data-nct'),id);const t=data.trials.find(t=>t.nct_id===id);for(const v of ['#attrition-map','#parallel .trial-lines','#dumbbell'])assert.equal(await count(`${v} [data-trial="${id}"].selected`),t.pair?1:0);if(t.pair)assert.equal(await page.locator('#sankey svg').getAttribute('data-trial'),id);};
 const choose=async id=>{await page.fill('#search',id);await selected(id);};
 const verifySubset=async()=>{const st=await snapshot();const expected=pairs.filter(t=>(st.phase==='all'||st.phase===t.phase)&&(st.sponsor==='all'||st.sponsor===t.sponsor_class)&&Object.entries(st.activeBrushes).every(([key,[lo,hi]])=>{const v=key==='attrition'?100*t.attrition:key==='started'?t.started:key==='gap'?(st.gapMode==='signed'?t.pair.difference_pp:t.pair.absolute_difference_pp):t.completion_year;return v!=null&&v>=lo-1e-9&&v<=hi+1e-9;})).map(t=>t.nct_id).sort();assert.deepEqual(st.activeSubset.sort(),expected);assert.match(await page.locator('#subset-status').innerText(),new RegExp('^'+expected.length+' / 38'));
 for(const v of ['#attrition-map circle.trial-point','#parallel .parallel-line','#dumbbell g.pair']){const actual=await page.locator(v).evaluateAll(es=>es.filter(e=>!e.classList.contains('outside-subset')).map(e=>e.dataset.trial).sort());assert.deepEqual(actual,expected,v);}return expected;};
 await selected('NCT04019704');
 await page.locator('#attrition-map [data-trial="NCT02176291"]').hover();await selected('NCT04019704');await page.locator('#attrition-map [data-trial="NCT02176291"]').click();await selected('NCT02176291');
 await page.locator('#parallel .parallel-line[data-trial="NCT03433339"]').focus();await page.keyboard.press('Enter');await selected('NCT03433339');await page.keyboard.press('Escape');assert.equal(await page.locator('#tooltip').isVisible(),false);
 // Real pointer gestures, not injected brush state.
 async function brush(key,lowFraction,highFraction){const el=page.locator(`.pc-axis[data-axis="${key}"] .overlay`);await el.scrollIntoViewIfNeeded();const r=await el.boundingBox(),x=r.x+r.width/2;await page.mouse.move(x,r.y+r.height*lowFraction);await page.mouse.down();await page.mouse.move(x,r.y+r.height*highFraction,{steps:12});await page.mouse.up();}
 await brush('attrition',.5,.9);await brush('gap',.2,.8);assert.equal(Object.keys((await snapshot()).activeBrushes).length,2);await verifySubset();
 await page.selectOption('#sponsor-filter','INDUSTRY');await verifySubset();await page.selectOption('#phase-filter','PHASE3');await verifySubset();
 await page.selectOption('#report-status','subset');const expected=await verifySubset();assert.deepEqual((await page.locator('#matrix g.row').evaluateAll(es=>es.map(e=>e.dataset.trial))).sort(),expected);
 await page.click('#clear-filters');assert.equal((await snapshot()).activeSubset.length,38);assert.equal(await count('#matrix g.row'),38);await page.selectOption('#report-status','all');
 // Accessible exact ranges, inverted-range error, empty subset, and selected record outside it.
 await page.locator('#range-details>summary').click();await page.fill('#range-attrition-min','10');await page.fill('#range-attrition-max','40');await page.fill('#range-gap-min','5');await page.fill('#range-gap-max','20');await page.locator('#range-form button').click();await verifySubset();
 const previous=await snapshot();await page.fill('#range-gap-min','25');await page.fill('#range-gap-max','5');await page.locator('#range-form button').click();assert.match(await page.locator('#range-error').innerText(),/minimum/);assert.deepEqual((await snapshot()).activeBrushes,previous.activeBrushes);
 await page.fill('#range-gap-min','26');await page.fill('#range-gap-max','30');await page.locator('#range-form button').click();assert.equal((await verifySubset()).length,0);await choose('NCT04019704');assert.match(await page.locator('#selection-status').innerText(),/outside/);assert.equal(await count('#sankey .flow-terminal'),4);
 await page.click('#clear-filters');await page.fill('#range-year-min',String(Math.min(...pairs.filter(t=>t.completion_year!=null).map(t=>t.completion_year))));await page.fill('#range-year-max',String(Math.max(...pairs.filter(t=>t.completion_year!=null).map(t=>t.completion_year))));await page.locator('#range-form button').click();await verifySubset();assert.ok(!(await snapshot()).activeSubset.includes('NCT01488071'));await page.click('#clear-filters');
 await page.selectOption('#gap-mode','signed');await page.fill('#range-gap-min','-25');await page.fill('#range-gap-max','0');await page.locator('#range-form button').click();await verifySubset();await page.selectOption('#gap-mode','absolute');assert.equal((await snapshot()).activeBrushes.gap,undefined);await verifySubset();
 // All 38 live Sankeys: source counts, terminal counts/heights and ribbon endpoint thickness.
 for(const t of pairs){await choose(t.nct_id);const k=+(await page.locator('#sankey svg').getAttribute('data-count-scale'));assert.equal(+(await page.locator('#sankey svg').getAttribute('data-total')),t.started);
  for(const role of ['experimental','comparator'])for(const status of ['completed','not-completed']){const S=t.pair[role+'_started'],C=t.pair[role+'_completed'],n=status==='completed'?C:S-C;const rect=page.locator(`.flow-terminal[data-role="${role}"][data-status="${status}"]`);assert.equal(+(await rect.getAttribute('data-count')),n);assert.ok(Math.abs(+(await rect.getAttribute('height'))-n*k)<1e-8);const link=page.locator(`.flow-link[data-role="${role}"][data-status="${status}"]`);assert.equal(await link.count(),n>0?1:0);if(n>0){assert.ok(Math.abs(+(await link.getAttribute('data-width'))-n*k)<1e-8);const vals=(await link.getAttribute('d')).match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/gi).map(Number);assert.ok(Math.abs((vals[9]-vals[7])-n*k)<1e-8);}}
 }
 // Search resolves partial terms, nonpaired records remain missing rather than zero; row reveal is internal.
 await page.fill('#search','AXS-05');await page.locator('#search-results button[data-nct="NCT04019704"]').click();await selected('NCT04019704');
 await page.fill('#search','does-not-exist-xyz');assert.match(await page.locator('#search-results').innerText(),/No matching/);await page.keyboard.press('Escape');
 await choose('NCT00149643');assert.equal(await count('#sankey svg'),0);assert.match(await page.locator('#trial-detail').innerText(),/Flagged/);
 await page.reload();await page.waitForSelector('html[data-ready=true]');await selected('NCT00149643');await page.click('#reset');await selected('NCT04019704');
 for(const sort of ['signed','absolute','id']){await page.selectOption('#pair-sort',sort);const r=await page.locator('#dumbbell g.pair').evaluateAll(es=>es.map(e=>e.__data__));assert.ok(r.every((t,i)=>!i||(sort==='id'?r[i-1].nct_id<=t.nct_id:sort==='signed'?r[i-1].difference_pp>=t.difference_pp:r[i-1].absolute_difference_pp>=t.absolute_difference_pp)));}
 await page.locator('#dumbbell [data-trial="NCT02176291"]').click();await selected('NCT02176291');
 await page.selectOption('#report-status','review');assert.equal(await count('#matrix g.row'),119);const review=await page.locator('#matrix g.row').first().getAttribute('data-trial');await page.locator('#matrix g.row').first().focus();await page.keyboard.press('Space');await selected(review);assert.match(await page.locator('#trial-detail').innerText(),/No validated/);await choose('NCT04019704');assert.equal(await page.locator('#report-status').inputValue(),'all');for(const box of ['matrix','dumbbell']){assert.ok(await page.locator('#'+box).evaluate(el=>{const row=el.querySelector('[data-trial="NCT04019704"]'),a=row.getBoundingClientRect(),b=el.getBoundingClientRect();return a.top>=b.top-2&&a.bottom<=b.bottom+2;}),'Search reveals row in '+box);}await page.selectOption('#report-sort','year');
 await choose('NCT02176291');await page.locator('#record-details>summary').click();await page.locator('#reason-details>summary').click();await page.selectOption('#reason-mode','share');assert.match(await page.locator('#reason-detail').innerText(),/20.0%/);
 await page.click('#reset');assert.deepEqual((await snapshot()).activeBrushes,{});assert.equal((await snapshot()).activeSubset.length,38);assert.equal(await page.locator('#report-status').inputValue(),'all');assert.equal(await page.locator('#report-sort').inputValue(),'id');assert.equal(await page.locator('#reason-mode').inputValue(),'count');
 for(const width of [1440,1024,768,390]){await page.setViewportSize({width,height:1000});await page.reload();await page.waitForSelector('html[data-ready=true]');await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'document overflow '+width);assert.equal(await count('.primary-view'),5);if(width===1440)assert.ok(await page.evaluate(()=>document.querySelector('#selected-panel').getBoundingClientRect().left>document.querySelector('.map-area').getBoundingClientRect().right));if(width<=768)assert.ok(await page.evaluate(()=>document.querySelector('#selected-panel').getBoundingClientRect().top>document.querySelector('#attrition-map').getBoundingClientRect().bottom));await page.mouse.move(1,1);await page.screenshot({path:`/private/tmp/401-five-${width}.png`,fullPage:true});}
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 const result={result:'PASS',edition:'frozen-five-view-dashboard',primary_views:5,parallel_population:38,axes:['STARTED log2','overall attrition percent','absolute/signed gap pp','completion year'],live_sankeys_checked:38,all_map_coordinates_checked:true,real_pointer_multi_axis_brushing:true,mathematical_intersections_and_missing_year:true,search_selection_and_row_reveal:true,nonpaired_not_zero_filled:true,sorts_matrix_and_reason_controls:true,keyboard_and_reset:true,widths:[1440,1024,768,390],javascript_errors:errors,failed_assets:failed,source_sha256:Object.fromEntries(['five-view/index.html','five-view/app.js','five-view/style.css','five-view/dashboard-data.js','five-view/data.json','five-view/eligibility.json'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')]))};fs.writeFileSync('/private/tmp/401-five-browser.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
